import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { PredictiveReportFilters } from '../../components/PredictiveReport/PredictiveReportFilters';
import { PredictiveReportSummary } from '../../components/PredictiveReport/PredictiveReportSummary';
import { PredictivePredictionsTable } from '../../components/PredictiveReport/PredictivePredictionsTable';
import { PredictiveReportDownloads } from '../../components/PredictiveReport/PredictiveReportDownloads';
import { PredictiveHotspotsCard } from '../../components/PredictiveReport/PredictiveHotspotsCard';
import { PredictiveRecommendationsCard } from '../../components/PredictiveReport/PredictiveRecommendationsCard';
import { usePredictivePestReport } from '../../hooks/usePredictivePestReport';
import { getUserById } from '../../services/admin/users';
import useAuthStore from '../../services/Contexts/useAuthStore';
import {
  buildReportFilename,
  downloadPredictiveReportExcel,
  downloadPredictiveReportPdf,
} from '../../services/reports/predictiveReportsService';
import type { PredictiveReportQuery, Season } from '../../types/PredictiveReport';

/** Current season from the system month (matches the backend Temporada mapping). */
function currentSeason(): Season {
  const month = new Date().getMonth() + 1; // 1-12
  if (month >= 3 && month <= 5) return 'primavera';
  if (month >= 6 && month <= 8) return 'verano';
  if (month >= 9 && month <= 11) return 'otono';
  return 'invierno';
}

function triggerBlobDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

function ReportesPanel() {
  const [query, setQuery] = useState<PredictiveReportQuery | null>(null);
  const [isPdfLoading, setIsPdfLoading] = useState(false);
  const [isExcelLoading, setIsExcelLoading] = useState(false);
  const [exportError, setExportError] = useState<string | null>(null);

  const reportQuery = usePredictivePestReport(query);

  // Resolve the seller's own region (state) to pre-fill and auto-generate the
  // report for their zone when entering the tab. They can still change it by hand.
  const currentUser = useAuthStore((s) => s.user);
  const userDetailQuery = useQuery({
    queryKey: ['user-location', currentUser?.userId],
    queryFn: () => getUserById(currentUser!.userId),
    enabled: !!currentUser?.userId,
    staleTime: 10 * 60 * 1000,
  });
  const userRegion = userDetailQuery.data?.location?.stateName ?? '';
  const defaultSeason = useMemo(() => currentSeason(), []);

  const handleSubmit = useCallback((region: string, season: Season) => {
    setExportError(null);
    setQuery({ region, season });
  }, []);

  // Auto-generate once for the seller's zone when it first resolves.
  const autoGenerated = useRef(false);
  useEffect(() => {
    if (!autoGenerated.current && query === null && userRegion) {
      autoGenerated.current = true;
      setQuery({ region: userRegion, season: defaultSeason });
    }
  }, [userRegion, query, defaultSeason]);

  const handleDownloadPdf = useCallback(async () => {
    if (!query) return;
    setExportError(null);
    setIsPdfLoading(true);
    try {
      const blob = await downloadPredictiveReportPdf(query);
      triggerBlobDownload(blob, buildReportFilename(query, 'pdf'));
    } catch (error) {
      setExportError((error as Error).message ?? 'No se pudo descargar el PDF');
    } finally {
      setIsPdfLoading(false);
    }
  }, [query]);

  const handleDownloadExcel = useCallback(async () => {
    if (!query) return;
    setExportError(null);
    setIsExcelLoading(true);
    try {
      const blob = await downloadPredictiveReportExcel(query);
      triggerBlobDownload(blob, buildReportFilename(query, 'xlsx'));
    } catch (error) {
      setExportError((error as Error).message ?? 'No se pudo descargar el Excel');
    } finally {
      setIsExcelLoading(false);
    }
  }, [query]);

  const report = reportQuery.data;
  const hasReport = Boolean(report);

  return (
    <main
      data-testid="reportes-panel"
      className="min-h-full bg-[#F9FAFB] p-6 font-sans space-y-6"
    >
      <header className="space-y-1">
        <h1 className="text-2xl font-bold text-[#101828]">Reporte predictivo de plagas</h1>
        <p className="text-sm text-[#6B7280]">
          Consulta y descarga la prediccion de plagas por region y temporada para identificar
          oportunidades de venta.
        </p>
      </header>

      <PredictiveReportFilters
        key={userRegion || 'no-region'}
        initialRegion={userRegion}
        initialSeason={defaultSeason}
        isLoading={reportQuery.isFetching}
        onSubmit={handleSubmit}
      />

      {reportQuery.isError && (
        <div
          data-testid="report-error"
          className="rounded-lg border border-[#FCA5A5] bg-[#FEF2F2] p-4 text-sm text-[#991B1B]"
        >
          {reportQuery.error instanceof Error
            ? reportQuery.error.message
            : 'Ocurrio un error generando el reporte.'}
        </div>
      )}

      {exportError && (
        <div
          data-testid="export-error"
          className="rounded-lg border border-[#FCA5A5] bg-[#FEF2F2] p-4 text-sm text-[#991B1B]"
        >
          {exportError}
        </div>
      )}

      {reportQuery.isFetching && !hasReport && (
        <div
          data-testid="report-loading"
          className="rounded-xl border border-[#E5E7EB] bg-white p-6 text-sm text-[#6B7280]"
        >
          Generando reporte predictivo. Esto puede tardar unos segundos…
        </div>
      )}

      {hasReport && report && (
        <section className="space-y-4">
          <div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
            <h2 className="text-lg font-semibold text-[#101828]">
              Resultados para {report.region} – {report.season}
            </h2>
            <PredictiveReportDownloads
              disabled={!hasReport || reportQuery.isFetching}
              isPdfLoading={isPdfLoading}
              isExcelLoading={isExcelLoading}
              onDownloadPdf={handleDownloadPdf}
              onDownloadExcel={handleDownloadExcel}
            />
          </div>

          <PredictiveReportSummary report={report} />
          <PredictivePredictionsTable predictions={report.predictions ?? []} />
          <PredictiveHotspotsCard hotspots={report.hotspots ?? []} />
          <PredictiveRecommendationsCard recommendations={report.recommendations ?? []} />
        </section>
      )}

      {!hasReport && !reportQuery.isFetching && !reportQuery.isError && (
        <div
          data-testid="report-placeholder"
          className="rounded-xl border border-dashed border-[#D1D5DB] bg-white p-10 text-center text-sm text-[#6B7280]"
        >
          Selecciona una region y temporada para generar el reporte predictivo.
        </div>
      )}
    </main>
  );
}

export default ReportesPanel;
